alkemyTech/OT169-Java-server

src/main/java/com/alkemy/ong/entity/Activity.java
src/main/java/com/alkemy/ong/model/Activity.java
src/main/java/com/alkemy/ong/repository/ActivityRepository.java

Agregué:
**1. Activity Class**
- Anotación SQL para modificar el comando delete y que updatée la info de la propiedad softDelete en lugar de borrar el registro.
- Anotación Where para filtrar las busquedas de la base de datos según la propiedad softDelete
- Uso del método estático del Timestamp para generar uno cuando se crea un nuevo objeto.
**2. Activity Repository**
- Agregué el método findByName(String name) para buscar por nombre.

Ot169 21 - Crear modelo y repositorio base de Activities

---

src/main/java/com/alkemy/ong/entity/Member.java
src/main/java/com/alkemy/ong/repository/MemberRepository.java

Se creo la entidad Members de acuerdo a los parámetros de aceptación a continuación detallados y el repositorio correspondiente:
Criterios de aceptación: 
Nombre de tabla: members. Campos:
name: VARCHAR NOT NULL
facebookUrl: VARCHAR NULLABLE
instagramUrl: VARCHAR NULLABLE
linkedinUrl: VARCHAR NULLABLE
image: VARCHAR NOT NULL
description: VARCHAR NULLABLE
timestamps y softDelete

OT169-22 Crear modelo y repositorio base de Members

---

src/entity/Role.java
src/test/java/com/alkemy/ong/entity/Role.java

Summary
*Creation Role entity.

Role entity creation

---

src/main/java/com/alkemy/ong/entity/Slide.java
src/main/java/com/alkemy/ong/repository/SlideRepository.java

QUIERO gestionar las imágenes
PARA modificar eficientemente el contenido visual
Los Slides de la pantalla de inicio serán gestionados de forma dinámica por el administrador del sitio. 
Los mismos tendrán como campos imageUrl, text, order y organizationId (ya que pertenecerán una ONG).

Slide entity and repository added

---

src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationDto.java
src/main/java/com/alkemy/ong/service/impl/OrganizationService.java
src/main/java/com/alkemy/ong/utils/Mapper.java

SUMMARY
- **OrganizationService**
1. Inyecté _OrganizationRepository_
2. Pido los datos públicos de la organización a la base de datos y lo mapeo a un _OrganizationDTO_.
- **Mapper**
1. Alteré el método _mapToDto_ para recibir un _OrganizationEntity_, copiar alguno de los atributos al _OrganizationDto_ y devolverlo.
- **OrganizationDto**
1. Actualicé la clase para ajustarse a los tipos de los atributos propuestos en la clase _OrganizationEntity_.
**IMPORTANTE:**
Ahora que el _OrganizationDto_ funciona con la clase real _OrganizationEntity_ hay que **BORRAR** del main la clase _OrganizationMock_.

Ot169 23 - UPDATED Endpoint datos públicos de la Organización

---

src/main/java/com/alkemy/ong/entity/Activity.java
src/main/java/com/alkemy/ong/repository/ActivityRepository.java

SUMMARY
- Activity class
Vuelvo a subir el cambio en el tipo del atributo ID de UUID a String porque se sobreescribió con otro PR

OT169-21 - Crear modelo y repositorio base de Activities

---

src/main/java/com/alkemy/ong/dto/OrganizationDto.java

SUMMARY
- OrganizationDto
Cambié el tipo del atributo _phone_ a String para matchear con el cambio que hizo Silvia al atributo con el mismo nombre en el _OrganizationEntity_

OT169-23 - Endpoint datos públicos de la Organización

---

src/main/java/com/alkemy/ong/repository/OrganizationRepository.java

Change UUID to String in OrganizationRepository

Ot169 15 - Change UUID to String

---

src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

Endpoint de Eliminar usuario (OT169-32)
Descripción
COMO usuario
QUIERO eliminar mi usuario
PARA darme de baja del sistema
DELETE a /users/:id Deberá recibir el id del usuario con el método DELETE. 
El borrado debe ser lógico.

Endpoint to delete user

---

src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/service/NewsService.java
src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
src/main/java/com/alkemy/ong/utils/NewsMapper.java

Descripción
QUIERO ver los detalles de una novedad
PARA poder informar actualizaciones del contenido
GET a /news/:id . Mostrará todos los campos de una entry en base al id enviado por parámetro.

Endpoint Detalle Novedad(OT169-45)

---

src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/entity/News.java
src/main/java/com/alkemy/ong/service/NewsService.java
src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java

Descripción
QUIERO eliminar una actividad existente
PARA mantener la información actualizada
DELETE /news/:id - Deberá validar la existencia en base al id enviado por parámetro.
En el caso de que exista, eliminarla

Endpoint Eliminar Novedades(OT169-48)

---

src/main/java/com/alkemy/ong/controller/ContactController.java

COMO usuario
QUIERO dar de alta contactos
PARA que estén en la base de datos
Se debe hacer una petición POST /contacts 
-Se verificará que la petición contenga los campos name y email

OT169-54: Endpoint para almacenar contactos

---

src/main/java/com/alkemy/ong/controller/UserController.java
src/main/java/com/alkemy/ong/entity/User.java
src/main/java/com/alkemy/ong/service/UserService.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

QUIERO visualizar un listado de Usuarios
PARA mantener un seguimiento de quiénes forman parte del sistema
GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores

OT169-35 Endpoint para listar Usuarios

---

d
src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideRequestDto.java
src/main/java/com/alkemy/ong/dto/SlideResponseDto.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
src/main/java/com/alkemy/ong/utils/SlideMapper.java

Descripción
QUIERO ver el detalle de Slides
PARA ver el contenido de forma más detallada.
Se debe hacer una peticion GET a /Slides/:id . 
Mostrará todos los campos del slide en base al id enviado por parámetro. 
En el caso de que no exista, devolverá un error con un código de estado 404
Se aplico toda la lógica perdida de la rama OT169-56

EndPoint RolllBack SlideDetails

---

src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideDto.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

QUIERO ver el listados de Slides
PARA ver el contenido de forma gráfica.
Se debe hacer una petición GET a /Slides. 
Devolverá el listado de Slides, con la imagen y el orden del mismo

OT169-55 : Endpoint Listado de Slides

---

README.md
src/main/java/com/alkemy/ong/entity/User.java
src/main/resources/data.sql

Agregué data.sql con scripts para: 
* Creación de los roles ADMIN y USER. 
* Creación de 10 administradores y 10 usuarios.

OT169-72: Crear Seeder de Usuarios

---

src/main/java/com/alkemy/ong/controller/ActivityController.java
src/main/java/com/alkemy/ong/controller/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationRequestDto.java
src/main/java/com/alkemy/ong/entity/Organization.java
src/main/java/com/alkemy/ong/entity/Slide.java
src/main/java/com/alkemy/ong/repository/OrganizationRepository.java
src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/OrganizationService.java
src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java
src/main/java/com/alkemy/ong/utils/SlideMapper.java

OT169-63 - Agregar campos de contacto a organizations
**SUMMARY**
1. **OrganizationEntity**
- Cambié el nombre de la clase a _Organization_ para que todos los modelos estén nombrados bajo el mismo criterio y actualicé todas las referencias a la clase. Por eso hay tantas clases modificadas.
- Agregué los campos de contacto facebookUrl, linkedinUrl, instagramUrl según especificaba el ticket.
2. **OrganizationService**
- Cambié el nombre a OrganizationServiceImpl para matchear los demás.
3. **ActivityService**
- Cambié el nombre a ActivityServiceImpl para matchear los demás.
**TICKET:**
QUIERO editar los campos de contacto a la Organización
PARA mostrar la información de la mejor manera posible. 
Modificar modelo, repositorio y servicio …

Ot169 63 - Agregar campos de contacto a organizations

---

src/main/java/com/alkemy/ong/dto/OrganizationRequestDto.java
src/main/java/com/alkemy/ong/dto/OrganizationResponseDto.java
src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

**SUMMARY**
1. **OrganizationRequestDto**
- Agregué los campos *facebookUrl*, *linkedinUrl*, *instagramUrl* validados para guardarlos en la base de datos.
2. **OrganizationResponseDto**
- Agregué los campos arriba mencionados para poder devolverlos en la respuesta. 
Los envolví en un HashMap<String, String> para poder agruparlos junto con el email.
3. **Mapper**
- Modifiqué los métodos para agregar los campos nuevos y la lógica del HashMap en el *mapToDto()*.
4. **OrganizationServiceImpl**
- Modifiqué el método *postPublicInfo()* para postear los datos del *OrganizationRequestDto*
Agregó los pedidos POST y GET en Postman para ver como quedaría expuesta la data.
**TICKET**
COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página
PARA poder acceder a ellas.
Criterios de …

Ot169 64 - Modificar endpoint público de organizations para devolver links de redes sociales

---

src/main/java/com/alkemy/ong/entity/Comment.java
src/main/java/com/alkemy/ong/repository/CommentRepository.java
src/main/java/com/alkemy/ong/service/ICommentService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java

**SUMMARY**
1. **Comment**
- Cree la entidad para agregar comentarios a las **News** de la aplicación. 
La misma tiene dos mapeos unidireccionales **@ManyToOne**, uno hacia **News** y otro hacia **User**.
2. **Comment Repository**
- Agregué el repositorio para trabajar con la nueva entidad.
3. **ICommentService**
- Agregué la interfáz que va a implementar el servicio. Aún no declaré ningún método.
4. **CommentServiceImpl**
- Creé el servicio de la entidad pero aún no tiene implementado ningún método.
*Imagenes de referencia del mapeo*
**TICKET**
COMO usuario 
QUIERO agregar un nuevo comentario a una novedad
PARA opinar acerca de dicha novedad
Se agregará la posibilidad de agregar Comentarios a una Novedad. Los campos de un comentario serán user_id, body y news_id

OT169-74 created Comment Entity and Repository

---

src/main/java/com/alkemy/ong/config/SecurityConfig.java
src/main/java/com/alkemy/ong/controller/ContactController.java
src/main/java/com/alkemy/ong/dto/ContactDto.java
src/main/java/com/alkemy/ong/service/ContactService.java
src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

Descripción
QUIERO obtener el listado de contactos
PARA llevar un control de los contactos recibidos.
GET /contacts - Devolverá todos los registros de contactos. Este endpoint solo podrá ser accedido por un usuario administrador.

OT169-61: Endpoint para listar contactos

---

src/main/java/com/alkemy/ong/config/SecurityConfig.java
src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/dto/CommentResponseDto.java
src/main/java/com/alkemy/ong/service/ICommentService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

**SUMMARY**
1. **CommentController**
- Creé el controlador para los comentarios con la ruta `/comment` y le inyecté el servicio.
- Agregué un @GetMapping para devolver una lista de CommentResponseDto a partir del método del servicio.
2. **CommentResponseDto**
- Dto para devolver solo el campo *body* de los objetos Comment.
3. **ICommentService**
- Declaré el método *getAllComments()* que debe devolver una lista de CommentResponseDto.
4. **CommentServiceImpl**
- Inyecté el repositorio.
- Implementé el método *getAllComments()*, el cual: 
a. Llama al método *findAll(Sort sort)* del repositorio, para devolver los comentarios de la base de datos y ordenar los resultados en base a la propiedad *timestamp* de manera descendente (el primer comentario siempre será el más reciente).
b. Mapea cada …

OT169-75 Endpoint para listar Comentarios

---

src/main/java/com/alkemy/ong/controller/CategoriesController.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/service/CategoryService.java
src/main/java/com/alkemy/ong/service/MemberService.java

This PR adds:
> MemberRepository
> MemberService
> MemberController: With creation endpoint

OT169-69: Member Creation endpoint

---

src/main/java/com/alkemy/ong/controller/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideUpdateDto.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

COMO usuario administradorQUIERO poder actualizar Slides PARA tener la información actualizada al comienzo de la página
Se debe hacer una petición PUT /Slides/:id 
Deberá validar que el slide existe y actualizarlo, caso contrario devolver un error.
Tareas realizadas:
- Creación URI correspondiente al endpoint de actualización.
- Creación de método correspondiente en SlideService y SlideServiceImpl.
- Lógica de validaciónes agregadas.
- Se agrega el método para mapear entidad a dto a la clase donde se encuentras los demás mappers.
- Funcionamiento del código comprobado.

OT169-58 Slide EndPoint Actualización Slide

---

src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/dto/TestimonialDto.java
src/main/java/com/alkemy/ong/service/TestimonialService.java
src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

Endpoint Creación Testimonios OT169-65
QUIERO dar de alta nuevos Testimonios
PARA informar Novedades acerca de la ONG.
POST /testimonials - Deberá validar la existencia de los campos name y content enviados, 
para almacenar el registro en la tabla testimonials.

Endpoint Creación Testimonios OT169-65

---

src/main/java/com/alkemy/ong/controller/CategoriesController.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/resources/data.sql

- Agregué el método getAllUsers en el controlador de Members.
- Agregué el método getAllMembers en el service de Members para recuperar nombre y descripción de cada miembro de la organización. 
- Adjunto screenshot de respuesta en Postman
----------------------------------------------------
COMO administrador
QUIERO listar los Miembros
PARA obtener información certera de los Miembros al día.
GET /members - Devolverá todos los Miembros

OT169-68: Endpoint para listar Miembros

---

src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/dto/CommentRequestDto.java
src/main/java/com/alkemy/ong/repository/NewsRepository.java
src/main/java/com/alkemy/ong/service/ICommentService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

COMO usuario
QUIERO dar de alta nuevos Comentarios
PARA agregarlos a un post existente
POST /comments - Deberá validar que se envíe el campo post_id,user_id y body
****RESUMEN****
*COMMENT CONTROLLER
-->Se agrego el endpoint "/post" que recibe un CommentRequestDto con los siguientes datos: user_id,post_id y body
*NEWS REPOSITORY
-> Se agrego la anotacion @Repository 
*ICommentService
-> Se agrego a la interfaz el método addCommerce
*COMMENT SERVICE IMPL
-> Se implemento el método addComment que recibe un CommentRequestDto. Devuelve un 404 si no encuentra al usuario o post dado. Si pasa dichas validaciones, guarda un nuevo comentario relacionado con el post y el user. Finalmente devuelve un código 200.
*MAPPER
-> Se agrego el método …

OT169-76 Comment´s post endpoint added

---

src/main/java/com/alkemy/ong/controller/AuthController.java
src/main/java/com/alkemy/ong/dto/UserCredentialsDto.java
src/main/java/com/alkemy/ong/service/AuthService.java
src/main/java/com/alkemy/ong/service/impl/AuthServiceImpl.java

**SUMMARY**
1. **AuthController**
- Cambié el método *login()*, reemplacé el @RequestParams que recibía 2 argumentos por un @RequestBody que recibe un *UserCredentialsDto* con el email y la contraseña. También valida que sean provistas con un @Valid.
2. **AuthService**
- Cambié el tipo de argumento que recibe el método *login()* para recibir un *UserCredentialsDto*.
3. **AuthServiceImpl**
- Cambié el método *login()* para recibir los nuevos parámetros.
- Dentro de la implementación del método, alteré las líneas que recibían los datos viejos por las propiedades del nuevo objeto.
4. **UserCredentialsDto**
- Creé un objeto con las propiedades *email* y *password* para transportar las credenciales de un usuario que quiere acceder al sistema.
*Nueva manera de autenticarse en la app:* …

OT169-99 - BUG FIX: /login

---

src/main/java/com/alkemy/ong/controller/TestimonialController.java
src/main/java/com/alkemy/ong/entity/Testimonial.java
src/main/java/com/alkemy/ong/service/TestimonialService.java
src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java

Descripción
QUIERO eliminar Testimonios
PARA moderar los Testimonios y Novedades acerca de la ONG.
DELETE /testimonials/:id - Deberá validar que el testimonio existe y eliminarlo, 
caso contrario devolver un error

Endpoint eliminación de Testimonios OT169-67

---

src/main/java/com/alkemy/ong/controller/NewsController.java
src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java

TAREAS:
1. Eliminación de la inyección del repositorio en el controlador de news.
2. Acomodar método delete  en el newsServiceImpl.

Elimination of the injection in the news controller

---

src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/service/ICommentService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java

COMO usuario
QUIERO borrar un comentario
PARA moderar el contenido
DELETE /comments/:id - Deberá validar la existencia del comentario. Solamente podrán eliminar un comentario el usuario creador del mismo o un administrador. Deberá devolver un código de error 404 si el comentario no existe, o 403 si no tiene permiso para modificarlo.

OT169-78: Endpoint Eliminación Comentarios

---

src/main/java/com/alkemy/ong/controller/CommentController.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/entity/Comment.java
src/main/java/com/alkemy/ong/repository/CategoryRepository.java
src/main/java/com/alkemy/ong/repository/CommentRepository.java
src/main/java/com/alkemy/ong/service/ICommentService.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java

El error surgió porque se eliminaron tickets ya mergeados. Se procedió a incorporar al main el código de los tickets ya subidos y aprobados.

OT169-103 Corrección de tickets eliminados 

---

src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/dto/MemberDto.java
src/main/java/com/alkemy/ong/dto/MembersResponseDto.java
src/main/java/com/alkemy/ong/repository/MemberRepository.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/utils/Mapper.java

**SUMMARY**
1. **MemberController**
- Agregué @RequestParam al método *getAll()* para pasarle el número de página que quiero devolver al servicio, en caso de no pasar ninguno usará 0 como valor por default.
2. **MembersResponseDto**
- Creé un dto específico para separar la información de los miembros y las URLs de las páginas anterior y siguiente en la respuesta del pedido.
_Devolverá un List<MemberDto> members y un Map<String, String> pages._
3. **MemberDto**
- Creé un dto para filtrar y ordenar las propiedades que devuelvo de los miembros. En este caso solo devolverá el nombre y la descripción.
4. **MemberService**
- Alteré el método *getAll()*. Ahora recibirá un Integer page para filtrar por página y devolverá un MembersResponseDto.
```
a. Devuelve una página con 10 Member usando el …
```

Ot169 82 - Agregar paginación a Miembros

---

src/main/java/com/alkemy/ong/config/SecurityConfig.java

Se corrigió el bug donde si se alteraba el jwt o no se ingresaba el mismo devolvía un código de error 403. Se camino para que devuelva el código correcto, un 401.

OT169-104 Solved 403 instead of 401 bug

---

src/main/java/com/alkemy/ong/controller/AuthController.java

**SUMMARY**
1. **AuthController**
- Documenté los diferentes métodos del endpoint para describir que hace cada uno de ellos y sus respuestas.
- Los modelos ya habían sido previamente documentados por @Facundo98 .
- Castié el return type del método *getAuthenticateUserData()* a un ResponseEntity<UserDto> para que muestre el modelo de respuesta en Swagger.
```
public ResponseEntity<UserDto> getAuthenticateUserData(HttpServletRequest httpServletRequest) {
return authService.getAuthenticatedUserData(httpServletRequest);
}
```
->
```
public ResponseEntity<UserDto> getAuthenticateUserData(HttpServletRequest httpServletRequest) {
return (ResponseEntity<UserDto>) authService.getAuthenticatedUserData(httpServletRequest);
}
```
**IMAGENES DE COMO QUEDÓ EN SWAGGER**
**TICKET**
```
COMO desarrollador …
```

OT169-89 - Agregar documentación a Autenticación

---

src/main/java/com/alkemy/ong/controller/NewsController.java

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Novedades
PARA tener referencias de su funcionamiento
Criterios de aceptación:Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.
*Se agregaron las anotaciones correspondientes para generar documentación con Swagger.

Agregar documentacion a News- Ticket OT169-86

---

src/main/java/com/alkemy/ong/controller/CategoriesController.java

This PR:
- Adds the Swagger UI Documentation to the CategoriesController
- Fixes a minor bug in CategoriesController

OT169-85: Swagger documentation added

---

src/main/java/com/alkemy/ong/controller/MemberController.java

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Miembros
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

OT169-87: Agregar documentación a Miembros

---

src/main/java/com/alkemy/ong/entity/User.java

Se agregaron las validaciones faltantes que pedía el ticket OT169-17

OT169-107 Fixed lost validation

---

src/main/java/com/alkemy/ong/controller/ContactController.java
src/main/java/com/alkemy/ong/service/ContactService.java
src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
src/main/java/com/alkemy/ong/utils/Mapper.java
src/test/java/com/alkemy/ong/controller/ContactControllerTest.java

MODIFICACIONES:
1. Cambie la entidad que ingresa al controlador por un dto para generar las validaciones de los campos nombre y email ya que la entidad no posee las validaciones.
Eso me llevo a modificar el método save de la clase service y generar un método mapper 
public static Contact mapFromDto(ContactDto contactDto, Contact contact){
contact.setId(contactDto.getId());
contact.setName(contactDto.getName());
contact.setPhone(contactDto.getPhone());
contact.setEmail(contactDto.getEmail());
contact.setMessage(contactDto.getMessage());
return contact;
}
2. Modifique los catch de los endpoint ya que ambos poseían not found 
Cambie el not found por un bad request 
@PostMapping
public ResponseEntity<?> save(@Valid @RequestBody ContactDto dto) throws Exception {
try{
ContactDto contact1 = …

OT169-95: Endpoints /contact

---

src/main/java/com/alkemy/ong/controller/MemberController.java

MODIFICACIONES: 
1. En la paginación este input no tiene ninguna utilidad 
2. Eliminar este campo de access token ya que es redundante 
Ya que al ingresar el token en este campo aplica para todo los endpoints

OT169-108 : Fixing Modificar documentación de la clase member controller

---

pom.xml
src/main/java/com/alkemy/ong/config/SwaggerConfig.java
src/main/java/com/alkemy/ong/controller/AmazonController.java
src/main/java/com/alkemy/ong/controller/MemberController.java
src/main/java/com/alkemy/ong/service/impl/AuthServiceImpl.java
src/test/java/com/alkemy/ong/controller/AuthControllerTest.java

- Agrego dependencia, plugin, exclusiones y properties en POM para configurar Jacoco. 
- Corrección en AuthControllerTest
- Corrección en AuthServiceImpl
- Corrección en MemberController
- Agrego tipo de dato en AmazonController para poder subir archivos desde Swagger
- Configuro parámetro a ignorar en SwaggerConfig
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------

Configuración Jacoco
